name: taskpay
description: "TaskPay - Connect task posters with student taskers"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  intl: ^0.17.0
  appwrite: ^14.0.0
  url_launcher: ^6.3.1
  window_manager: ^0.4.3
  cupertino_icons: ^1.0.8
  
  # TaskPay specific dependencies
  flutter_paystack: ^1.0.7
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  image_picker: ^1.0.4
  equatable: ^2.0.5

dependency_overrides:
  flutter_web_auth_2: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true